In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies = pd.read_csv(r'E:\PythonLibraries\CSV\imdb-top-1000.csv')
movies.head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [3]:
ipl = pd.read_csv(r'E:\PythonLibraries\CSV\deliveries.csv')
ipl.sample(3)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
168444,11152,1,Delhi Capitals,Sunrisers Hyderabad,2,5,S Dhawan,P Shaw,Mohammad Nabi,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
36166,155,1,Deccan Chargers,Rajasthan Royals,17,2,WPUJC Vaas,DR Smith,YK Pathan,0,...,0,0,0,0,0,0,0,WPUJC Vaas,caught,LA Carseldine
89079,377,1,Rajasthan Royals,Mumbai Indians,11,3,SR Watson,STR Binny,DR Smith,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [4]:
#groupby use to a catogarical method 
genres = movies.groupby('Genre')
genres

In [5]:
#applying builtin aggregation function 
genres.min().head(5)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0

In [19]:
#find the top 3 genres bu total earning 
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [20]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [21]:
#find the genre with highest avg IMDB rating 
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(2)

Genre
Western    8.350000
Crime      8.016822
Name: IMDB_Rating, dtype: float64

In [22]:
#find director with most popularity 
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(2)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Name: No_of_Votes, dtype: int64

In [23]:
#find the highest rated movies of each genre
movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(2)

Genre
Drama    9.3
Crime    9.2
Name: IMDB_Rating, dtype: float64

In [26]:
#find number of movies for each actors\
#movies['Star1'].value_counts()
movies.groupby('Star1').size().sort_values(ascending=False).head(3)

Star1
Tom Hanks         12
Robert De Niro    11
Clint Eastwood    10
dtype: int64

Groupby attribute and Methods

In [ ]:
#find a total number of groups -->len
len(movies.groupby('Genre'))

14

In [ ]:
#size
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
#first()
genres = movies.groupby('Genre')
genres.first()
#last()
genres.last()
genres.nth()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.0
34,Whiplash,2014,106,Drama,8.5,Damien Chazelle,Miles Teller,717585,13092000.0,88.0
70,Mononoke-hime,1997,134,Animation,8.4,Hayao Miyazaki,Yôji Matsuda,343171,2375308.0,76.0
95,Amélie,2001,122,Comedy,8.3,Jean-Pierre Jeunet,Audrey Tautou,703810,33225499.0,69.0
107,Amadeus,1984,160,Biography,8.3,Milos Forman,F. Murray Abraham,369007,51973029.0,88.0
137,Queen,2013,146,Adventure,8.2,Vikas Bahl,Kangana Ranaut,60701,1429534.0,NaN
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0

In [33]:
#getGroup
genres.get_group('Horror').head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0

In [36]:
genres.groups
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [43]:
#agg method 
#passing dict
genres.agg(
    {
        'Runtime':'min',
        'Gross':'sum',
        'IMDB_Rating':'mean',
        'No_of_Votes':'max'
    }
)

           Runtime         Gross  IMDB_Rating  No_of_Votes
Genre
Action          45  3.263226e+10     7.949419      2303232
Adventure       88  9.496922e+09     7.937500      1512360
Animation       71  1.463147e+10     7.930488       999790
Biography       93  8.276358e+09     7.938636      1213505
Comedy          68  1.566387e+10     7.901290       939631
Crime           80  8.452632e+09     8.016822      1826188
Drama           64  3.540997e+10     7.957439      2343110
Family         100  4.391106e+08     7.800000       372490
Fantasy         76  7.827267e+08     8.000000        88794
Film-Noir      100  1.259105e+08     7.966667       158731
Horror          71  1.034649e+09     7.909091       787806
Mystery         96  1.256417e+09     7.975000      1129894
Thriller       108  1.755074e+07     7.800000        27733
Western        132  5.822151e+07     8.350000       688390

In [24]:
#split (apply) combine 
#apply --> builtin functions 
genres.apply(min).head(5)

C:\Users\rushi\AppData\Local\Temp\ipykernel_16728\909757725.py:3: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min).head(5)
C:\Users\rushi\AppData\Local\Temp\ipykernel_16728\909757725.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min).head(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN

In [36]:
#find number of movies starting with A for Each Group 

def foo(group):
    return (group['Series_Title'].str.startswith('A')).sum()

In [37]:
genres.apply(foo)

C:\Users\rushi\AppData\Local\Temp\ipykernel_16728\2904676014.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [38]:
#find ranking of each movies in the group according to IMDB score
def rank_movie(group):
    group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
    return group

In [41]:
genres.apply(rank_movie).sample(5)

C:\Users\rushi\AppData\Local\Temp\ipykernel_16728\699269207.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_movie).sample(5)

                                       Series_Title Released_Year  Runtime  \
Genre
Biography 359                    Dallas Buyers Club          2013      117
Adventure 984                      The Muppet Movie          1979       95
Action    982                             Mad Max 2          1981       96
Drama     433  Vivre sa vie: Film en douze tableaux          1962       80
          501                         Les choristes          2004       97

                   Genre  IMDB_Rating              Director  \
Genre
Biography 359  Biography          8.0      Jean-Marc Vallée
Adventure 984  Adventure          7.6         James Frawley
Action    982     Action          7.6         George Miller
Drama     433      Drama          8.0       Jean-Luc Godard
          501      Drama          7.9  Christophe Barratier

                             Star1  No_of_Votes        Gross  Metascore  \
Genre
Biography 359  Matthew McConaughey       441614   27298285.0       80.0
Adventure 984           Jim Henson        32802   76657000.0       74.0
Action    982           Mel Gibson       166588   12465371.0       77.0
Drama     433          Anna Karina        28057  482545511.0        NaN
          501        Gérard Jugnot        57430    3635164.0       56.0

               genre_rank
Genre
Biography 359        35.0
Adventure 984        68.0
Action    982       160.0
Drama     433       124.0
          501       160.0

In [43]:
#find the normalize IMDB rating groups wise 
def normal(group):
    group['normalized_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
    return group

In [44]:
genres.apply(normal).sample(6)

C:\Users\rushi\AppData\Local\Temp\ipykernel_16728\3050146873.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal).sample(6)

,,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,normalized_rating
Genre,,,,,,,,,,,,
Biography,729,The Theory of Everything,2014,123,Biography,7.7,James Marsh,Eddie Redmayne,404182,35893537.0,72.0,0.076923
Adventure,267,Stand by Me,1986,89,Adventure,8.1,Rob Reiner,Wil Wheaton,363401,52287414.0,75.0,0.500000
Crime,180,To Kill a Mockingbird,1962,129,Crime,8.2,Robert Mulligan,Gregory Peck,293811,504340883.0,88.0,0.375000
Biography,328,Lion,2016,118,Biography,8.0,Garth Davis,Dev Patel,213970,51739495.0,69.0,0.307692
Animation,70,Mononoke-hime,1997,134,Animation,8.4,Hayao Miyazaki,Yôji Matsuda,343171,2375308.0,76.0,0.800000
Comedy,132,"Three Billboards Outside Ebbing, Missouri",2017,115,Comedy,8.2,Martin McDonagh,Frances McDormand,432610,54513740.0,88.0,0.600000

In [48]:
# groupby on multiple cols

duo = movies.groupby(['Director', 'Star1'])

# size
duo.size()

# get_group
duo.get_group(('Aamir Khan', 'Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [50]:
#find the best (in - terms of metascore(avg) actors --> genre combo)
movies.groupby(['Star1', 'Genre'])['Metascore'].mean().reset_index().sort_values('Metascore', ascending=False)

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]